services:
  cells:
    ports: !reset []
    networks:
      - default
      - denox_ingress
    labels:
      caddy: files.tools.denox-corp.com
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy.header.Strict-Transport-Security: "max-age=31536000"
      caddy.encode: "gzip zstd"
      denox.auth: public

networks:
  denox_ingress:
    name: denox_ingress
    external: true
